// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by JasperApi.
NSObject<FlutterMessageCodec> *JasperApiGetCodec(void);

@interface JasperApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)startBleScanWithCompletion:(void(^)(NSString *_Nullable, NSError *_Nullable))completion;
- (void)connectBleDeviceMacAddress:(nullable NSString *)macAddress completion:(void(^)(NSString *_Nullable, NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
